### ISSUE TITLE
Argument to pad with NAs when n > 1

### ISSUE THREAD

**Issue by datalove** [kevinushey/RcppRoll#1]
Hi Kevin, just wondering if you might consider including an option to pad the returned vectors/matrices with NAs when n > 1? 

I'd love to be able to do something like this

`data.frame(a = 1:10, b = roll_sum(1:10, 3, padNA = TRUE))`

instead of this

`data.frame(a = 1:10, b = c(rep(NA,2),roll_sum(1:10, 3)))`.

Of course `data.frame(a = 1:x, b = roll_sum(1:x, n = 3))` throws an error because length of `roll_sum(x,n)` for n > 1 is shorter than `length(1:x)`.

**Comment by kevinushey** [comment]
`fill` has now been implemented in a way that conforms with the behaviour of `zoo`'s `rollapply` function, with the caveat that I still maintain the alternative default behaviour for the `roll_r` and `roll_l` functions.
