### ISSUE TITLE
Update to CRAN version

### ISSUE THREAD

**Issue by robjhyndman** [kevinushey/RcppRoll#13]
Hi Kevin. I am using your RcppRoll package from github, and will use it as a dependency in a package I am writing for identifying anomalous time series. In order to upload my package to CRAN, it would be useful if the CRAN version of RcppRoll was updated to match the version on github. Would that be possible?

Thanks.
Rob

**Comment by kevinushey** [comment]
Hi Rob,

Thanks! Glad you're finding the package useful. I think I'll try to take a look at #12 first, and aim for a submission sometime by the end of the month. Would that be sufficient?

Kevin

**Comment by robjhyndman** [comment]
That would be great. Thanks.

**Comment by kevinushey** [comment]
Thanks for your patience -- I've now begun the submission process and the new version of RcppRoll should appear on CRAN in the next couple days.

**Comment by robjhyndman** [comment]
Thanks Kevin.
