### ISSUE TITLE
not working with by > 1

### ISSUE THREAD

**Issue by pasturm** [kevinushey/RcppRoll#14]
With the by argument set to > 1 the left out points are returned as random/uninitialized values.
Example:
`roll_mean(rep(1,20), n = 3, by = 3)`
`[1]  1.000000e+00 1.071419e+200 9.385277e+223  1.000000e+00  4.311955e-80  1.840099e-80  1.000000e+00  7.724200e-37  2.647809e-32`
`[10]  1.000000e+00  1.426530e-71 3.791529e+179  1.000000e+00  3.315553e-33 5.391965e+241  1.000000e+00 7.096584e-110 9.486060e-322`

A workaround is:
`foo = roll_mean(rep(1,20), n = 3, by = 3)`
`foo = foo[seq(1, length(foo), by = 3)]`
but it would be nice if this was done inside the `roll_` functions.

**Comment by kevinushey** [comment]
This should be fixed with the latest version on GitHub (sorry, not on CRAN yet). Can you try installing with:

    devtools::install_github('kevinushey/RcppRoll')

and let me know if you still see the issue?

**Comment by kevinushey** [comment]
Whoops, I lied -- there is definitely something amiss here as it only occasionally produces the correct result! I'll dig in deeper.

**Comment by mt1022** [comment]
Is this fixed now?

**Comment by kevinushey** [comment]
This is resolved in the development version of `RcppRoll`:

```
devtools::install_github("kevinushey/RcppRoll")
```

I really should make a CRAN submission one of these days ...
