### ISSUE TITLE
Using RcppRoll with Performance Analytics

### ISSUE THREAD

**Issue by debsush** [kevinushey/RcppRoll#15]
Hi,

I would like to use the functions defined in Performance Analytics package like Burke Ratio, MaxDrawdown and Sharpe Ratio and then roll them using your package as I believe your package will give me substantial performance benefits.  My knowledge in C++ is limited and it would be very difficult for me to recreate those R functions available in Performance Analytics package in C++.  I would like to know if I can use your package to roll those R functions or do I have to rewrite them in C++?

Regards
SD

**Comment by kevinushey** [comment]
I think you'll have to write them in C++, unfortunately. Hopefully in the future we'll provide some tools for creating custom rollable functions more easily.
