### ISSUE TITLE
Using user defined function in RcppRoll

### ISSUE THREAD

**Issue by statquant** [kevinushey/RcppRoll#19]
Hello, I recently came across RcppRoll, sorry for the stupid question but is the `rollit` function allow the use of a user defined function (R function or cpp function). 
I kind of see that calling a r function from Rcpp might be even worse than looping in R itself, but it would provide some kind of sugar is some cases. Typically using data.table by or equivalent dplyr behaviour one could call rolling functions by groups...
Do I understand correctly ?
If yes even if it seems trivial it might be worth adding a few words in the vignette so people won't expect this feature (and spend time trying :) ).

Thanks for providing this package to the community

**Comment by kevinushey** [comment]
I've decided to remove `rollit()` from this package for now due to the maintenance burden + the awkward interface -- sorry for the trouble.
