### ISSUE TITLE
rollit function not available

### ISSUE THREAD

**Issue by fderyckel** [kevinushey/RcppRoll#21]
Hi Kevin, 
I hope you are well.  Greetings from Lusaka.
I have installed RcppRoll through gitub
`devtools::install_github("kevinushey/RcppRoll")`

I have tried the standards function roll_mean, roll_sum, roll_sd. They work great.    Now I want to create my own rolling function with `rollit`.  But there is not such function in the package. 

What am I missing?

**Comment by kevinushey** [comment]
This function is still available in the CRAN version of `RcppRoll`, but is no longer available in the development versions.

That was available with previous versions of the `RcppRoll` package, but I decided to remove it as it was a bit of a kludge and it seemed to not provide all that much utility to most users. Sorry about that :-/

**Comment by fderyckel** [comment]
Thanks Kevin for the update.
Best,
François

2017-05-03 20:00 GMT+02:00 Kevin Ushey <notifications@github.com>:
