### ISSUE TITLE
Align = "middle" vs "center"

### ISSUE THREAD

**Issue by mkiang** [kevinushey/RcppRoll#28]
For `roll_mean()`, the documentation specifies `align` can be `{"left", "middle", "right"}` but the function specifies `{"left", "center", "right"}`.

Lines 36 and 23 of this file: https://github.com/kevinushey/RcppRoll/blob/master/R/RcppRoll.R

**Comment by kevinushey** [comment]
Thanks! Sorry for taking so long to get to this.
