### ISSUE TITLE
roll_sum overwrites weights when renormalizing them

### ISSUE THREAD

**Issue by wilfriedgh** [kevinushey/RcppRoll#31]
A bothering and quite dangerous bug is that the weights renormalization **overwrites the given weights vector**, instead of creating an inner temporary one : 

```
a = 1:25
> d <- data.frame(w = c(0.2, 0.1, 0.1, 0.05, 0.05) ) # the total weight is 0.5 on purpose
> d
     w
1 0.20
2 0.10
3 0.10
4 0.05
5 0.05
> roll_sum(a, n = length(d$w), weights = d$w)
 [1]  11.5  16.5  21.5  26.5  31.5  36.5  41.5  46.5  51.5  56.5
       61.5  66.5  71.5  76.5  81.5  86.5  91.5  96.5 101.5 106.5 111.5

> d
    w
1 2.0
2 1.0
3 1.0
4 0.5
5 0.5
```

The fix should be quite simple, just creating a local weight vector inside the functions

More over, the weights renormalization seems to be enabled by default, which might be nice to mention in the popup help.

Thanks for all the work and this wonderful library.

**Comment by mschilli87** [comment]
@wilfriedgh 
> The fix should be quite simple [...]

Maybe you could open a pull request then?
This should increase the probablity of a fast fix. :wink:

**Comment by wilfriedgh** [comment]
It's a bit of a beginner question, but I do not usually work with Github : do I have to clone, fix and suggest a pull request to do so?

**Comment by kevinushey** [comment]
Should be fixed as per https://github.com/kevinushey/RcppRoll/commit/3036c2f15f7e8acf8a3ab00f8bba0a665adf808b#diff-2be426a9fa144e8c5a0b7465f2261ae4R108. You can test with:

```
devtools::install_github("kevinushey/RcppRoll")
```

Thanks for reporting!

**Comment by wilfriedgh** [comment]
Oh, didn't see your reply. Thanks ! I will look into it in the days to come

**Comment by wilfriedgh** [comment]
Thank you so much Kevin for your efficiency and your reactivity!

I can't install the fix now because of our company policy (GitHub is blocked through our VPN), but will update as soon as CRAN releases it.

I've been advertising your package around me, will continue even more!
Thanks again.
